GET http://localhost:8000/data/languages/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJPcGVuUGhvbmljcy1KV1QtSXNzdWVyIiwiYXVkIjoiaHR0cHM6Ly9hcGkub3BlbnBob25pY3MuY29tIiwidXNlcklkIjoiZmVmYzhkYzAtOWYyNC00Y2U5LWEwNTktN2EyYWMyNDZmYzE2In0.e02zsgQRMdILOZ3GfhvOcGREcixetI7x2lGUTDkye60

{
  "depth": 2
}
